### ISSUE TITLE
librdata reading numeric column twice

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#10]
Hi, 

I am just trying to understand a bit how librdata works. 
I am executing readEx with the attached Rds file (produced in R 3.5.1). This file has a dataframe with two columns, the first being a numeric one (1,2,3) and the second a factor (a,b,c). What I get printed is the first column twice, first as a double, next as an integer. Maybe librdata was written against an older version of rds files? I get the same when running against an RData file.  

Read table: (null)
Read column: (null) with 3 elements of type Real
1.000000 2.000000 3.000000
Read value label: a at 0
Read value label: b at 1
Read value label: c at 2
Read column: (null)  with 3 elements of type Integer
1 2 3
Read column name: num index0
Read column name: char index1
Error code 0

thanks
[one.zip](https://github.com/WizardMac/librdata/files/2699210/one.zip)

**Comment by evanmiller** [comment]
Factors are stored as integers, and treated as labeled values - you're seeing two different columns that happen to have the same numeric values. Try storing (1, 2, 3, 4, 5, 6) and (a, a, b, b, c, c) to see what I mean.

**Comment by ofajardo** [comment]
OK got it, thanks.
So that means if I start getting labels, that means the next column coming is the true integer representation of that column. What I am wondering is how to know the information about what column am I collecting, since the functions do not give a column index as argument. Am I correct on my thinking that basically it is just a sequential process therefore I don't need a column index? Or is it any other strategy to know let's say to what column the labels I am collecting belong to?

**Comment by evanmiller** [comment]
Yes, the value label handler is called on all the factor levels immediately before the relevant column handler is called.

librdata calls the handlers as it encounters the data structures in the file - so yes, it is a sequential process, with very little internal state stored between handler calls.
