### ISSUE TITLE
pyreadr: new python binding for librdata

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#11]
Hi, 

I have created a python package "pyreadr" which makes librdata available for python users. It also uses jamovi-readstat from @jonathon-love as wrapper.

The repo is here: https://github.com/ofajardo/pyreadr

Please let me know if I should pay attention to anything (licensing, citing, etc).

If you like the project, it would be nice if you could list it as language binding in your README, as you do in ReadStat.

**Comment by evanmiller** [comment]
Added, thanks!
