### ISSUE TITLE
decompress files in chunks

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#17]
I am not sure how difficult this would be in terms of changes needed to librdata, so it's a just a suggestion:

Some people is having difficulties while reading files which after decompressing are big, see for example [this](https://github.com/ofajardo/pyreadr/issues/3). Basically they get a unable to allocate memory error.

I think the problem comes from rdata_read.c, for zip:

```
if (inflateInit2(ctx->z_strm, (15+32)) != Z_OK) {
        retval = RDATA_ERROR_MALLOC;
        goto cleanup;
    }
```

My interpretation is that zlib uncompresses everything into RAM, which means you really need a lot of RAM if the file is big enough. Once the process is over this step the RAM consumption shrinks dramatically.

Would it be possible to decompress & read in chunks? 
Maybe there is other workarounds?

thanks

**Comment by jonathon-love** [comment]
a memory mapped file would be a good solution here - when it overflows ram it spills to disk. however, i don't think there's a "nice" way to do this cross platform. the mm file APIs on windows and unix are completely different.

**Comment by ofajardo** [comment]
although this could be nice, the real blocker right now is #19

**Comment by evanmiller** [comment]
The decompression already occurs in chunks.
