### ISSUE TITLE
Memory error when reading long vectors

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#19]
When reading a RData file that has long vectors, a RDATA_ERROR_MALLOC may arise. 

After some analysis, it seems the error comes from rdata_read.c line 1106. The problem is in the function rdata_malloc, line 89:

```
static void *rdata_malloc(size_t len) {
if (len > MAX_BUFFER_SIZE || len == 0)
return NULL;

return malloc(len);
}
```

It seems to me the value of MAX_BUFFER_SIZE is too low for numeric vectors. As an example I attach a file with one vector of 2**22 rows of double values. Trying to read this file throws a memory error. I manually increased the max_buffer size to 1<<30 and then it was fine.

Would it be possible to increase that max buffer size value? Why was that specific value chosen?

[2pow22_double.Rdata.tar.gz](https://github.com/WizardMac/librdata/files/3025580/2pow22_double.Rdata.tar.gz)

This would solve [this issue]( https://github.com/ofajardo/pyreadr/issues/3) (but partially, as it seems that issue points at two different problems, the second one already reported)
IT would also solve (partially, because they also report a problem with ReadStat in the same issue) [this other issue](https://github.com/jamovi/jamovi/issues/689) in jamovi

**Comment by evanmiller** [comment]
Hi, the max buffer size is designed to guard against massive allocations in the presence of malformed input or a bug in the code. It made more sense in the row-oriented ReadStat library but maybe should be eliminated here.

**Comment by evanmiller** [comment]
Fixed in https://github.com/WizardMac/librdata/commit/b7ca1252b670d60a6e8d3c8ce6fcc8ab3b43d6ab

**Comment by ofajardo** [comment]
some people using pyreadr are still complaining about this issue, even with the current higher limit. Would it be possible to remove it for good? With the increasing size of datasets nowadays I would say that is reasonable.

**Comment by evanmiller** [comment]
Okay, it's gone:

https://github.com/WizardMac/librdata/commit/ba28c3ba1bb224901b873ce477282f61a51c567e

**Comment by ofajardo** [comment]
thanks!

**Comment by yasharth-tn** [comment]
plz resolve this error @ofajardo , I am getting this error: **LibrdataError:** Unable to convert string to the requested encoding . getting no way to resolve it
my rds file is around 31MB

**Comment by ofajardo** [comment]
@yasharth-tn A new version of pyreadr 0.3.0 is now out in pypi and it will be available on conda forge in a few hours. Please give it a try with the new version.
However I have to say that your error message points at something else and not at what is discussed in this issue.
If as I fear the new version does not solve your issue please open a new issue and post a sample file and code to reproduce. If no way to reproduce, we cannot help.
