### ISSUE TITLE
during installation, running "make" gives a libtool error

### ISSUE THREAD

**Issue by peiyaoli2** [WizardMac/librdata#20]
$ make
      CC       src/librdata_la-CKHashTable.lo
      CC       src/librdata_la-rdata_bits.lo
      CC       src/librdata_la-rdata_error.lo
      CC       src/librdata_la-rdata_io_unistd.lo
      CC       src/librdata_la-rdata_parser.lo
      CC       src/librdata_la-rdata_read.lo
    src/rdata_read.c: In function 'read_st_bzip2':
    src/rdata_read.c:124:49: warning: left shift count >= width of type [-Wshift-count-overflow]
      124 |             ((long)ctx->bz_strm->total_out_hi32 << 32);
          |                                                 ^~
    src/rdata_read.c:137:49: warning: left shift count >= width of type [-Wshift-count-overflow]
      137 |             ((long)ctx->bz_strm->total_out_hi32 << 32) - start_out;
          |                                                 ^~
      CC       src/librdata_la-rdata_write.lo
      CCLD     librdata.la
    libtool:   error: can't build x86_64-w64-mingw32 shared library unless -no-undefined is specified
    make: *** [Makefile:710: librdata.la] Error 1
I'm using mingw64 on windows.

**Comment by peiyaoli2** [comment]
$ make
      CC       src/librdata_la-CKHashTable.lo
      CC       src/librdata_la-rdata_bits.lo
      CC       src/librdata_la-rdata_error.lo
      CC       src/librdata_la-rdata_io_unistd.lo
      CC       src/librdata_la-rdata_parser.lo
      CC       src/librdata_la-rdata_read.lo
      CC       src/librdata_la-rdata_write.lo
      CCLD     librdata.la
    libtool:   error: can't build x86_64-w64-mingw32 shared library unless -no-undefined is specified
    make: *** [Makefile:710: librdata.la] Error 1
Hi, it seems like only the warnings are gone but the error is still there for me.

**Comment by evanmiller** [comment]
I set up AppVeyor to build on Windows, and it is failing with the same error you reported. Will investigate.

**Comment by evanmiller** [comment]
Okay, seems to be fixed now in https://github.com/WizardMac/librdata/commit/4ace02a0c02dc25da420eed73d9f47850a9f9b22m

**Comment by peiyaoli2** [comment]
Seems to work now, thanks!
