### ISSUE TITLE
Support for recognizing date objects

### ISSUE THREAD

**Issue by peiyaoli2** [WizardMac/librdata#21]
Hi!

As a follow up to #12, is there any plans for recognizing date objects separately from real values?

Thanks a lot!

**Comment by peiyaoli2** [comment]
I made a small change to add in support for `RDATA_TYPE_DATE` here: https://github.com/peiyaoli2/librdata/commit/db8e0d8bae5f124686073bf634e61be42452cccf

**Comment by evanmiller** [comment]
Thanks for bring up the issue and for the patch. I've reworked it a bit, including write support:

https://github.com/WizardMac/librdata/commit/bdd40b97b3716a99d071a1c48e99344ee58d5b8c

Please open a new issue if you find any bugs or have other feature suggestions.
