### ISSUE TITLE
wrong column name for Date vectors

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#24]
If I save a vector "a" of Real into an RData file (a.RData), and these lines in readEx.c in handle_column

```
printf("LEN: %d\n", (int)strlen(name));
printf("NULL: %d\n", name==NULL);
```

I get a as the name of the column.

Read table: a
Read column: a with 3 elements of type Real
LEN: 1
NULL: 0
1.000000 2.000000 3.000000
Error code 0

However if I do the same with a vector of Dates "d", I get a string of length 0 instead of the "d":

Read table: d
Read column:  with 4 elements of type Date
LEN: 0
NULL: 0
18091.000000 -64282.000000 0.000000 nan
Error code 0

The problem with this is that in pyreadr I am checking if name is NULL. In this case however I get a string of length 6 instead of 0 (no idea why) with random characters that break the conversion to utf-8 and make the process to fail. 

Would it be possible to make it consistent and make the name of the column "d"?

For rds data (included for completeness) the behavior is consistent with name NULL for both real and dates vectors. Not sure what should be the result there, maybe "a" and "d" again?

[colnames.zip](https://github.com/WizardMac/librdata/files/3390339/colnames.zip)

**Comment by evanmiller** [comment]
Do you still see this behavior? In the current version the RData files open OK for me.

**Comment by ofajardo** [comment]
Oh, pyreadr is behind librdata, particularly I am missing the commit from Apr 30 regarding RDATA_PSEUDO_SXP_ALTREP. Let me update and try again.

**Comment by ofajardo** [comment]
yes, indeed after updating pyreadr code to the lastest librdata version, now this issue is solved.

Thanks!
