### ISSUE TITLE
Support for ALTREP [deferred_string] function

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#29]
I have here an apparently inoffensive rds file with one single character vector of two elements, each with the value "14901". When trying to read it "Unable to read from file" error arises. I don't see anything special on it. The file was saved using R 3.6.1. 

File attached

Thanks for the help!
[RR2.zip](https://github.com/WizardMac/librdata/files/4556715/RR2.zip)

**Comment by evanmiller** [comment]
Thanks for the report. It looks like some new internal attributes were added to the R format in version 3. I'll work on it.

**Comment by evanmiller** [comment]
This file appears to use an ALTREP structure - still trying to understand it. Can you please provide the EXACT steps used to create this file?

**Comment by ofajardo** [comment]
@pedrohcrocha could you please explain the steps to reproduce this file?

**Comment by evanmiller** [comment]
This file uses the `deferred_string` function, which stores strings in the file as double-precision numbers (!). Now that I have started to crack the `ALTREP` structure I should have a fix soon.

**Comment by evanmiller** [comment]
Try https://github.com/WizardMac/librdata/commit/49200c1bbac39ce2eb7ece60a95dc3ec0971918e

**Comment by ofajardo** [comment]
looks good! thanks!

**Comment by evanmiller** [comment]
Okay great. I expect there to be similar errors in the future, so don't hesitate to open new bug reports.

I have added debugging information, so if you have an error handler set up, it will now report the name of the unrecognized class (function) in an `ALTREP` structure.
