### ISSUE TITLE
Support for ALTREP [compact_intseq] function

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#31]
The attached file raises such an error. Here the code to reproduce it:

```
library(tidyverse)
df <- tibble(x=1:10)
write_rds(df, 'tmp.rds', compress='gz')
```

while this one works

```
library(tidyverse)
df <- tibble(x=as.integer(c(1,2,3,4,5,6,7,8,9,10)))
write_rds(df, 'tmp.rds', compress='gz')
```

While the error message is different it looks similar to #29 
[tmp.rds.zip](https://github.com/WizardMac/librdata/files/4862536/tmp.rds.zip)

referenced from [here](https://github.com/ofajardo/pyreadr/issues/35)

**Comment by evanmiller** [comment]
This file also looks like it contains a `PSEUDO_SXP_ALTREP` structure so it is likely the same underlying issue as #34 and #29.

**Comment by ofajardo** [comment]
The error can be also obtained if trying to save a simple numeric base R vector, meaning it does not depend on objects created by external Rlibraries (assuming the underlying issue is the same). That also means at the moment dataframes created with new versions of R are not readeable in with libradata:

code and sample file:

```
vec <- 1:10
df <- data.frame(vec)
save(df, file = "simple.Rdata")
```

[simple.Rdata.zip](https://github.com/WizardMac/librdata/files/5130786/simple.Rdata.zip)

**Comment by evanmiller** [comment]
Please try https://github.com/WizardMac/librdata/commit/27b1e13e0178275b6995dbbb41959ff0cdd2a68e

It appears that R is storing just the sequence information (10, 1, 1) rather than the actual numbers. With this `ALTREP` stuff it looks we will have a lot more work adding support for various internal R functions. I will keep track of them in individual issues.

**Comment by ofajardo** [comment]
all of the sample files here look good now!
Not closing the issue as I am not sure if you want to keep it open or not.
