### ISSUE TITLE
LibrdataError: Unable to allocate memory

### ISSUE THREAD

**Issue by belimmohsin** [WizardMac/librdata#33]
Hi,

I am using pyreadr package, when I tried to read an "test.rdata" file it thew below error.
LibrdataError: Unable to allocate memory

Not able to figure out why this happened.

**Comment by ofajardo** [comment]
Please provide a sample file or a way to reproduce the issue (like the code to generate the data). Otherwise it is impossible to help.

**Comment by evanmiller** [comment]
Hi, if you can provide a test file I will try to figure out what's going on.

**Comment by evanmiller** [comment]
The maximum buffer size has been eliminated in https://github.com/WizardMac/librdata/commit/ba28c3ba1bb224901b873ce477282f61a51c567e.

If you are still experiencing problems please open a new issue with a complete test case.
