### ISSUE TITLE
Support for ALTREP [wrap_real] function

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#34]
hi

When reading the attached file which contains a dataframe with two numeric columns I get the error:

```
Invalid file, or file has unsupported features
```

Interestingly if I open it in R and save it again, I get the same error, but if I slice the dataframe conserving all the elements (stderror[1:152,]), then it opens OK. 

[stderror.RData.zip](https://github.com/WizardMac/librdata/files/5042524/stderror.RData.zip)

thanks in advance

**Comment by evanmiller** [comment]
It looks like the library is choking on a `PSEUDO_SXP_ALTREP` structure. I'll let you know if I make any progress on it.

**Comment by evanmiller** [comment]
Please try https://github.com/WizardMac/librdata/commit/27b1e13e0178275b6995dbbb41959ff0cdd2a68e

This file uses R's `wrap_real` function. Please confirm that the values produced by librdata are what you expect (e.g. not scaled or transformed in any way).

**Comment by ofajardo** [comment]
hmm, I am still getting the same error for this one.

**Comment by evanmiller** [comment]
My mistake – it was working for a minute but then I must have broken it while working on `compact_intseq`.

**Comment by evanmiller** [comment]
Okay, try the latest code.

**Comment by evanmiller** [comment]
(Reopen the issue if the data is incorrect)

**Comment by ofajardo** [comment]
looks good! thanks!
