### ISSUE TITLE
segfault with python binaries

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#35]
Hi There, 

I have a weird error in pyreadr that I hope you can help me to solve:

Until librdata commit ba28c3ba1bb224901b873ce477282f61a51c567e on Aug 26 everything was fine. But starting on the next commit 27b1e13e0178275b6995dbbb41959ff0cdd2a68e on Sept 11, altough on my dev machine everything was fine, travis jobs were failing with compilation errors in rdata_read.c about I should compile with the std=c99 flag. See below for the errors. These errors appear on travis for linux only and not for Mac, and windows on appveyour is fine too. I maintained the pyreadr code the same between librdata changes for testing, so I can tell the problem is coming from librdata.

I corrected the errors by introducing the flag -std=c99 for travis only (since on my machine that would make it to fail) and apparently everything was fine, travis compiles and runs the tests succesfully. However just now it was reported [here](https://github.com/ofajardo/pyreadr/issues/56) and I can confirm that the python wheels (binaries) produced by the travis job seg fault when trying to read any R file in any other machine. 

Any suggestion?

Thanks in advance!

Here the last succesful build with commit from Aug 26
https://travis-ci.com/github/ofajardo/pyreadr_wheels2/jobs/439123757
Here the failing build with commit from Sept 11
https://travis-ci.com/github/ofajardo/pyreadr_wheels2/jobs/439126418

Here the relevant errors:

```
pyreadr/libs/librdata/src/rdata_read.c: In function ‘read_st_z’:
  pyreadr/libs/librdata/src/rdata_read.c:267:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (bytes_written == len)
                             ^
  pyreadr/libs/librdata/src/rdata_read.c: In function ‘lseek_st’:
  pyreadr/libs/librdata/src/rdata_read.c:381:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           } else if (read_st(ctx, buf, len) != len) {
                                             ^
  pyreadr/libs/librdata/src/rdata_read.c: In function ‘rdata_parse’:
  pyreadr/libs/librdata/src/rdata_read.c:693:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (is_rdata && v2_header.format_version != header_line[3] - '0') {
                                                ^
  pyreadr/libs/librdata/src/rdata_read.c: In function ‘read_character_string’:
  pyreadr/libs/librdata/src/rdata_read.c:949:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (length == -1 || length == 0) {
                  ^
  pyreadr/libs/librdata/src/rdata_read.c: In function ‘read_compact_intseq’:
  pyreadr/libs/librdata/src/rdata_read.c:1110:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
           for (int i=0; i<vals[0]; i++) {
           ^
  pyreadr/libs/librdata/src/rdata_read.c:1110:9: note: use option -std=c99 or -std=gnu99 to compile your code
  pyreadr/libs/librdata/src/rdata_read.c: In function ‘read_string_vector_n’:
  pyreadr/libs/librdata/src/rdata_read.c:1267:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (string_length + 1 > buffer_size) {
                                 ^
  pyreadr/libs/librdata/src/rdata_read.c:1290:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                   if (4*string_length + 1 > utf8_buffer_size) {
                                           ^
  pyreadr/libs/librdata/src/rdata_read.c: In function ‘read_value_vector’:
  pyreadr/libs/librdata/src/rdata_read.c:1376:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (read_st(ctx, vals, buf_len) != buf_len) {
                                       ^
  pyreadr/libs/librdata/src/rdata_read.c:1384:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for (i=0; i<buf_len/sizeof(double); i++) {
                          ^
  pyreadr/libs/librdata/src/rdata_read.c:1389:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for (i=0; i<buf_len/sizeof(uint32_t); i++) {
                          ^
  pyreadr/libs/librdata/src/rdata_read.c: In function ‘recursive_discard’:
  pyreadr/libs/librdata/src/rdata_read.c:1554:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for (i=0; i<length; i++) {
                          ^
  error: command 'gcc' failed with exit status 1
```

**Comment by ofajardo** [comment]
OK using std=gnu99 solves the issue. Do you think that's good for my project? (at least on linux). gnu11 is good as well as seem to be the default these days, maybe that's better?

I don't understand why the compiler was not complaining before tough.

I also don't understand why if the default these days is std=gnu11 it needs that flag, although it may be that the toolchain I am using is using centos somehow and that has gcc 4.8 which still is in std=90 or 89 I think.

**Comment by evanmiller** [comment]
Hi, I think we can enforce C99 in configure.ac:

https://stackoverflow.com/questions/11647208/where-to-add-a-cflag-such-as-std-gnu99-into-an-autotools-project

**Comment by evanmiller** [comment]
(Unless you are copying sources and compiling without the autoconf toolchain)

**Comment by ofajardo** [comment]
yes, I am copying sources right now as it is the cannonical way to build python extensions.

It's fine, the people from the python toolchain I am using clarified me they are using centos which has an old gcc, that's why. The difference between c99 and gnu99 should not be, they suggested me to file an issue about that.

So, all good now, thanks!
