### ISSUE TITLE
Reading arrays with a 0 length dimension

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#37]
When reading an array with non 0 dimensions (array_simple.rds) the new code works like a charm!

But when reading an array where one dimension is 0 (array_onlyrow.rds and array_onlycol.rds) or just 1 dimension (array_onedim.rds), an error arises: Unable to allocate memory.

See attached file for the examples:

[arrays.zip](https://github.com/WizardMac/librdata/files/5647921/arrays.zip)

**Comment by evanmiller** [comment]
CC @peiyaoli2

**Comment by evanmiller** [comment]
Please try the latest code and see if that fixes things

**Comment by ofajardo** [comment]
hmm, I am getting a compilation error:

```
librdata.c:1858:14: error: dereferencing pointer to incomplete type ‘struct unistd_io_ctx_s’
 1858 |   __pyx_v_ctx->fd = __pyx_v_fd;
```

**Comment by evanmiller** [comment]
Try updating the header file as well and clean out any intermediate files. I renamed some symbols to avoid conflicts with ReadStat.

**Comment by ofajardo** [comment]
Yep thanks, a couple of renaming and now it is compiling fine again ... now testing ...

**Comment by ofajardo** [comment]
the error is gone, but now my handle_column function is receiving a count of 0 elements, so I am not retrieving data ... the dimensions seem to be correctly set to [12 0]

now I am working in the branch issue-36 just in case

**Comment by evanmiller** [comment]
@ofajardo Which file(s) does the new issue apply to?

**Comment by ofajardo** [comment]
array_onlyrow.rds, array_onlycol.rds and array_onedim.rds

**Comment by evanmiller** [comment]
These matrixes appear to be empty

```
> readRDS("Downloads/arrays/array_onedim.rds")
     
 [1,]
 [2,]
 [3,]
 [4,]
 [5,]
 [6,]
 [7,]
 [8,]
 [9,]
[10,]
[11,]
[12,]

> readRDS("Downloads/arrays/array_onlycol.rds")
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]

> readRDS("Downloads/arrays/array_onlyrow.rds")
     
 [1,]
 [2,]
 [3,]
 [4,]
 [5,]
 [6,]
 [7,]
 [8,]
 [9,]
[10,]
[11,]
[12,]
```


Matrix with data:

```
readRDS("Downloads/arrays/array_simple.rds")
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12
```

**Comment by ofajardo** [comment]
OOPS! Sorry, my bad! I was playing and saved the wrong arrays into the rds files, while the correct arrays are being read correctly by librdata, therefore no error! So, all good now!
Sorry again!
