### ISSUE TITLE
Should column headers be picked up?

### ISSUE THREAD

**Issue by eddelbuettel** [WizardMac/librdata#4]
If I set `debug=1` I see

```
edd@rob:~/git/librdata(feature/reader_example)$ ./readEx 
Read table: my_table
Read column: (null) with 3 elements
Read column: (null) with 3 elements
Read text value: hello at 0
Read text value: goodbye at 1
Read text value: (null) at 2
Error 0
edd@rob:~/git/librdata(feature/reader_example)$ 
```

Should we not see column headers `column1` and `column2` from [here](https://github.com/WizardMac/librdata/blob/master/writeEx.c#L20-L21) ?

**Comment by evanmiller** [comment]
Depending on the internal representation, column names sometimes appear after the data. There is a separate `rdata_column_name_handler` for this case. I'll update `readEx.c`.

**Comment by evanmiller** [comment]
https://github.com/WizardMac/librdata/commit/588a64317c1b53bf8b65a7c76287a0a698e8f32f
