### ISSUE TITLE
extern "C" missing

### ISSUE THREAD

**Issue by HaukeBartsch** [WizardMac/librdata#40]
In order to use the library in my test program (ubuntu 20.04) I had to include the header file with:

extern  "C" {
#include <rdata.h>
}

Without the "extern "C"" the linker was reporting that none of the functions where found. It would be good if the library would handle this internally.

**Comment by evanmiller** [comment]
Thanks, should be fixed in https://github.com/WizardMac/librdata/commit/00c1d2fe27990601d6f122fa129ebee75c7099a2
