### ISSUE TITLE
CMake-based build system

### ISSUE THREAD

**Issue by lopippo** [WizardMac/librdata#42]
Greetings, 
I am packaging librdata for Debian. I also intend to use it for my software that is ported to Win/mingw64 and Mac/port. To ease that, I am writing the build system based on the widely spread CMake build system. Would you accept a pull request when the whole process is set up ?
Indeed, while the win/mac build systems will have some specific paths tailored to my own setup, they will undoubtedly serve as an easily configurable template for others to use.

Thank you for making your software Free Software !
lopippo

**Comment by evanmiller** [comment]
Hi, you can see from the project's GitHub Actions that Mac, Windows, and Linux are all supported platforms. Is there some specific feature of CMake that you need that is not supported by autotools? I don't mind switching the project over to CMake, but I'd prefer not to maintain two sets of build tools.

**Comment by lopippo** [comment]
Thanks for your quick reply. Well, I did not realize that macOS was supported. Anyway, I did the CMake-ization also because it is easily maintainable and CMake is remarkably supported in general. The Debian package is ready!
Sincerely,
lopippo
